export interface Character {
	id: string;
	name: string;
	avatar: string;
	type: 'question' | 'answer';
}

export interface ChatMessage {
	characterId: string;
	content: string;
}

export interface ChatInterviewData {
	characters: Character[];
	messages: ChatMessage[];
	images: string[];
	background: string;
}

export const oneBodyAThousandWorldsChatInterview: ChatInterviewData = {
	characters: [
		{
			id: 'laura-butallo',
			name: 'Laura Butallo',
			avatar: '/media/artdao-question.webp',
			type: 'question'
		},
		{
			id: 'salawaki',
			name: 'sALAWAKI',
			avatar: '/media/one-body-a-thousand-worlds/interview/pfp1.webp',
			type: 'answer'
		}
	],
	messages: [
		{
			characterId: 'laura-butallo',
			content: 'Why did you decide to build your work around a specific character?'
		},
		{
			characterId: 'salawaki',
			content: 'Salawaki was born when I was creatively struggling toward the end of the pandemic. It was just a username I used at first, and then it turned into this character—generated with my real face and with a shirt over her head. I guess it happened while I was messing around with different 3D programs, trying to practice character animation. I didn\'t really plan for her to exist. She just kind of showed up—like Jesus? lol'
		},
		{
			characterId: 'laura-butallo',
			content: 'What kind of rules, history, and world does this character come with or create for itself?'
		},
		{
			characterId: 'salawaki',
			content: 'I\'m not really sure yet about Salawaki\'s history, but I know she\'s obsessed with trouts and always has them around. It\'s a bit weird, but who am I to judge? Lately I\'ve been thinking more about her, and maybe she\'s just a character that\'s meant to respond to contemporary issues. I\'m still figuring out what she really is—what her purpose is, and where she\'s going.'
		},
		{
			characterId: 'laura-butallo',
			content: 'Is your character an alter ego, an avatar or something else entirely?'
		},
		{
			characterId: 'salawaki',
			content: 'I see Salawaki as separate from me, even though she has my face and sometimes my personality. I don\'t really think of her as an alter ego—maybe more like a spokesperson for the stories I want to tell.'
		},
		{
			characterId: 'laura-butallo',
			content: 'How did that character transform over time?'
		},
		{
			characterId: 'salawaki',
			content: 'I love the little myths that have formed around Salawaki—how people interact with her and make memes about her. A couple of weeks ago I was researching Skibidi Toilet and thought, "Wow, this is just like Salawaki!" I like world-building, and I enjoy watching how people respond to her life events. Before Salawaki, I was researching how disinformation spreads online, especially in the Philippines. The people who create fake news are incredible at world-building. Maybe I got jealous and made my own world, haha'
		},
		{
			characterId: 'laura-butallo',
			content: 'What narratives do you think are generated by always showing the same being?'
		},
		{
			characterId: 'salawaki',
			content: 'One thing I really like is that I can create different worlds for her and make her do silly things. Sometimes I wonder if people are sick of her, but I think the layers and small myths keep it interesting. I hope she\'s not tired. I think she\'s separate from me, but she\'s still me (after all, she\'s my baby). A lot of what she says or does comes from things I\'ve experienced, or things that have happened to people close to me. So yes—it can be an encrypted autobiography.'
		}
	],
	images: [],
	background: '/media/one-body-a-thousand-worlds/interview/interview-bg.webp'
};

export const oneBodyAThousandWorldsChatInterviewTurro: ChatInterviewData = {
	characters: [
		{
			id: 'laura-butallo',
			name: 'Laura Butallo',
			avatar: '/media/artdao-question.webp',
			type: 'question'
		},
		{
			id: 'turro',
			name: 'TURRO',
			avatar: '/media/one-body-a-thousand-worlds/interview/pfp2.webp',
			type: 'answer'
		}
	],
	messages: [
		{
			characterId: 'laura-butallo',
			content: 'Why did you decide to build your work around a specific character?'
		},
		{
			characterId: 'turro',
			content: 'Before I started painting in a figurative style, I used to do lettering and graffiti. Over time, I realized that what I was painting didn\'t really reflect what I wanted to express. I had always been drawn to figurative art, so I began moving in that direction. The closest reference I had at the time were the characters that usually accompany graffiti lettering. As I kept practicing, I started questioning how I wanted to continue developing my work. That\'s when I decided to create el Turro, a character that allows me to represent the ideas I have, but also serves as an anchor point. This way, I can focus on improving my technique and make it easier to create a connection between one piece and the next. Over time, this continuity helps me build a more defined artistic identity.'
		},
		{
			characterId: 'laura-butallo',
			content: 'What kind of rules, history, and world does this character come with or create for itself?'
		},
		{
			characterId: 'turro',
			content: 'For me, the character represents the possibility of making a life through art while coming from a working-class background, in a society that places limits based on class and race. His image is tied to the stereotype of villero youth—people from marginalized neighborhoods who are often stigmatized. When the working class is represented in art, it\'s often from a victimizing or joyless perspective. What I\'m trying to do is show another side: one where pleasure, desire, luxury, and joy exist too. My own story is always present in the work. Most of it comes from real experiences. Even though there\'s surrealism, the starting point is real life. I don\'t see the character as an alter ego, but more like a figure that can represent many people.'
		},
		{
			characterId: 'laura-butallo',
			content: 'Is your character an alter ego, an avatar or something else entirely?'
		},
		{
			characterId: 'turro',
			content: 'The character doesn\'t follow strict rules or live in a fully built-out universe. But over time, I\'ve developed certain visual elements that keep things connected—like recurring symbols or moods. Those tools help the character move through different scenes and worlds while keeping a coherent style. I\'m not interested in giving him a fixed backstory because that would limit what I can do. I prefer him to stay open—someone who can shift depending on what I need to express. Still, there\'s a kind of logic that holds him together—something that stays the same even when the world around him changes. That lets me explore different realities while keeping the thread intact.'
		},
		{
			characterId: 'laura-butallo',
			content: 'How did that character transform over time?'
		},
		{
			characterId: 'turro',
			content: 'The worlds he moves through usually have surreal or dreamlike elements, but they\'re grounded in the everyday. They might seem a little unreal, but they\'re still believable. I\'m really interested in that mix of strange and familiar. Visually, I try to bring together elements from modern art with palettes and techniques that reference Renaissance painting. I add in streetwear, luxury objects, and small poetic details—like sunsets, butterflies, or calm landscapes that soften the mood. Even though I love building coherent environments for him, I see the character as autonomous. He can move between different settings without losing who he is. That freedom keeps the work flexible.'
		},
		{
			characterId: 'laura-butallo',
			content: 'What narratives do you think are generated by always showing the same being?'
		},
		{
			characterId: 'turro',
			content: 'I don\'t know exactly what narrative each viewer gets—that depends on the person. But I like to think that if I keep the style and message consistent, a connection forms over time. People might start to get curious about him, maybe even care about him or relate to what he represents. I\'m not trying to tell a fixed story. I just want to create a space for people to feel something. If someone looks at my work and feels something familiar or comforting, I think that\'s already something. I\'m interested in creating a quiet kind of relationship—where seeing him again doesn\'t feel repetitive, but instead invites you to look closer.'
		}
	],
	images: [],
	background: '/media/one-body-a-thousand-worlds/interview/interview-bg2.webp'
};

