export interface Project {
    title: string;
    subtitle: string;
    description: string;
    thumbnailPath: string[];
    thumbnailPathMobile: string;
    buttonPath: string;
    pagePath: string;
    artists: string[];
    artworks: string[]; 
    quote: string;
}

export const projects: Project[] = [
        {
                title: "Inherent Instability",
                subtitle: "NICØ, Elbi & Ina Vare",
                description: "“Every time I work with this equipment, something new happens—endless ways to connect each machine, it’s like creating a new network.”",
                thumbnailPath: [
                    "media/home/thumbnails-v2/inherent-instability/3.webp",
                    "media/home/thumbnails-v2/inherent-instability/2.webp",
                    "media/home/thumbnails-v2/inherent-instability/1.webp",
                ],
                thumbnailPathMobile: "media/home/thumbnails-v2-mobile/inherent-instability.webp",
                buttonPath: "media/home/buttons/03-button-inherent-instability.png",
                pagePath: "/inherent-instability",
                artists: ["NICØ", "Elbi", "Ina Vare"],
                artworks: ["No One Has Ever Seen a T-Rex", "NicØ playing", "Mercy"],
                quote: "“Every time I work with this equipment, something new happens — it’s like creating a new network.”",
        },
        {
                title: "Ecologies Of Code",
                subtitle: "Joaquina Salgado, Okytomo & Hypereikon",
                description: "“Water has a fascinating duality it's both a real-world element and a powerful symbol in our collective imagination.”",
                thumbnailPath: [
                    "media/home/thumbnails-v2/ecologies-of-code/3.webp",
                    "media/home/thumbnails-v2/ecologies-of-code/2.webp",
                    "media/home/thumbnails-v2/ecologies-of-code/1.webp",
                ],
                thumbnailPathMobile: "media/home/thumbnails-v2-mobile/ecologies-of-code.webp",
                buttonPath: "media/home/buttons/02-button-ecologies-of-code.png",
                pagePath: "/ecologies-of-code",
                artists: ["Joaquina Salgado", "Okytomo", "Hypereikon"],
                artworks: ["Untitled", "Guia", "Untitled"],
                quote: "“Water has a fascinating duality it’s both a real-world element and a powerful symbol.”",
        },
        {
                title: "Digital Matter",
                subtitle: "Marcus3D, Sulkian & Parsa",
                description: "“Digital mediums are like flying and physical mediums is like walking. It’s that kind of freedom.”",
                thumbnailPath: [
                    "media/home/thumbnails-v2/digital-matter/3.webp",
                    "media/home/thumbnails-v2/digital-matter/2.webp",
                    "media/home/thumbnails-v2/digital-matter/1.webp",
                ],
                thumbnailPathMobile: "media/home/thumbnails-v2-mobile/digital-matter.webp",
                buttonPath: "media/home/buttons/01-button-digital-matter.png",
                pagePath: "/digital-matter",
                artists: ["Marcus3D", "Sulkian", "Parsa"],
                artworks: ["Aero", "Pay to Win", "Digestive Delight"],
                quote: "“Digital mediums are like flying... and physical mediums is like walking. It’s that kind of freedom.",
        },
        {
            title: "Conversation with Operator",
            subtitle: "Ania Catherine, Dejha Ti & Jeff Davis",
            description: "“Jeff Davis sat down for an intimate conversation with the artistic duo Operator: Ania Catherine and Dejha exploring the creative process around their 3 act project Human Unreadable.”",
            thumbnailPath: [
                "media/home/thumbnails-v2/operator/3.webp",
                "media/home/thumbnails-v2/operator/2.webp",
                "media/home/thumbnails-v2/operator/1.webp",
            ],
            thumbnailPathMobile: "media/home/thumbnails-v2-mobile/operator.webp",
            buttonPath: "media/home/buttons/05-button-conversation-with-operator.png",
            pagePath: "/in-conversation",
            artists: ["Operator"],
            artworks: ["Human Unreadable", "Operator Interview", "Human Unreadable"],
            quote: "“When flesh meets algorithm, we expose the hidden values encoded in our technological systems—disrupting digital art's sterile perfection.“",
        },
        {
                title: "Body Frontier",
                subtitle: "VIXY, CYMOONV, BRENDY & CYSHIMI",
                description: "\"3D allows me to create worlds and characters, and to explore my identity through avatars that slowly transform, mutating between different elements.\"",
                thumbnailPath: ["media/home/thumbnails-v2/body-frontier/3.webp", "media/home/thumbnails-v2/body-frontier/1.webp", "media/home/thumbnails-v2/body-frontier/2.webp"],
                thumbnailPathMobile: "media/home/thumbnails-v2-mobile/body-frontier.webp",
                buttonPath: "media/home/buttons/10-button-body-frontier.png",
                pagePath: "/body-frontier",
                artists: ["VIXY", "CYMOONV", "BRENDY", "CYSHIMI"],
                artworks: ["Delirio", "Untitled", "Untitled"],
                quote: "\"3D allows me to create worlds and characters, and to explore my identity.\"",
        },
        {
                title: "Memetic Rubble",
                subtitle: "Julian Brangold & Fremzor",
                description: "\"Taking memes and processing them through AI, transforming them into something new is what makes memes exceptional. They lack ownership — inherently meant to be shared, remixed, and transformed by anyone.\"",
                thumbnailPath: ["media/home/thumbnails-v2/memetic-rubble/3.webp", "media/home/thumbnails-v2/memetic-rubble/2.webp", "media/home/thumbnails-v2/memetic-rubble/1.webp"],
                thumbnailPathMobile: "media/home/thumbnails-v2-mobile/memetic-rubble.webp",
                buttonPath: "media/home/buttons/12-button-memetic-rubble.png",
                pagePath: "/memetic-rubble",
                artists: ["Julian Brangold", "Fremzor"],
                artworks: ["Untitled", "Koko Context", "Untitled"],
                quote: "\"Taking memes and processing them through AI, transforming them into something new is what makes memes exceptional.\"",
        },
        {
                title: "Projected Emotional Technologies",
                subtitle: "Arvida Byström",
                description: "Projected Emotional Technologies studies outsourced affection: AI dolls, deepfake labor, and the economic exhaustion that makes synthetic intimacy feel pragmatic instead of dystopian.",
                thumbnailPath: [
                        "media/pet/project/project-1.webp",
                        "media/pet/project/project-2.webp",
                        "media/pet/project/project-3.webp"
                ],
                thumbnailPathMobile: "media/home/thumbnails-v2-mobile/pet.webp",
                buttonPath: "media/home/buttons/14-button-digital-archaeology.png",
                pagePath: "/pet",
                artists: ["Arvida Byström"],
                artworks: ["Harmony Diagnostics", "Deepfake Batch #17", "Quiet Logistics"],
                quote: "\"Arvida Byström's project PET arrives at a precise cultural moment: five million users subscribed to a single AI girlfriend app in its first month of operation.\"",
        },
        {
                title: "What's on your mind",
                subtitle: "Daniel Vasconcelos & H4wnee",
                description: "Artists weaponize platform mechanics—treating feeds, personas, and algorithms as mutable material—until the social web becomes a living studio where identity, attention, and resistance blur.",
                thumbnailPath: [
                        "media/whats-on-your-mind/carusel-1/daniel-gallery-2-1x.webp",
                        "media/whats-on-your-mind/carusel-1/daniel-gallery-3-1x.webp",
                        "media/whats-on-your-mind/carusel-2/h4wnee-gallery-1x.webp"
                ],
                thumbnailPathMobile: "media/home/thumbnails-v2-mobile/whats-on-your-mind.webp",
                buttonPath: "media/home/buttons/11-button-whats-on-your-mind.png",
                pagePath: "/whats-on-your-mind",
                artists: ["Daniel Vasconcelos", "H4wnee"],
                artworks: ["Platforms Limitations", "Daniel Vasconcelos", "H4wnee"],
                quote: "\"A new digital self emerges—distributed, reactive, endlessly iterated.\"",
        },
        {
                title: "Subconscious Media",
                subtitle: "Cyberspace has evolved into a realization platform where individual creative expressions reveal emergent patterns of collective thinking.",
                description: "\"More tools gives the possibility to better express what you don't quite know what it is. Even if you are unsure of the path, the important thing is not to lose what guides you, the essential, what really matters.\"",
                thumbnailPath: ["media/home/thumbnails-v2/subconscious-media/3.webp", "media/home/thumbnails-v2/subconscious-media/2.webp", "media/home/thumbnails-v2/subconscious-media/1.webp"],
                thumbnailPathMobile: "media/home/thumbnails-v2-mobile/subconscious-media.webp",
                buttonPath: "media/home/buttons/13-button-subconscious-media.png",
                pagePath: "/subconscious-media",
                artists: ["Vidal Herrera", "Gregorio Nash"],
                artworks: ["Untitled", "Observable Halo of a Comet Impact", "Influencer"],
                quote: "\"Cyberspace has evolved into a realization platform where individual creative expressions reveal emergent patterns of collective thinking.\"",
        },
        {
                title: "Digital Archaeology",
                subtitle: "PinkyBlu, Sabato, Stipin Pixel, Estelle Flores & CYDR",
                description: "We are constantly bombarded by new media — Yet, I remain influenced by the aesthetics of the past. Limitations offer a form of comfort when creating art.",
                thumbnailPath: ["media/home/thumbnails-v2/digital-archaeology/3.webp", "media/home/thumbnails-v2/digital-archaeology/1.webp", "media/home/thumbnails-v2/digital-archaeology/2.webp"],
                thumbnailPathMobile: "media/home/thumbnails-v2-mobile/digital-archaeology.webp",
                buttonPath: "media/home/buttons/14-button-digital-archaeology.png",
		pagePath: "/digital-archaeology",
                artists: ["PinkyBlu", "Sabato", "Stipin Pixel", "Estelle Flores", "CYDR"],
                artworks: ["PinkyBlu", "Artifact", "Sabato"],
                quote: "\"Transforming retro aesthetics into critique unearthing how even our interfaces carry ideology, and how friction can liberate artists from the polish of the present.\"",
        },
        {
                title: "Queering the Web3",
                subtitle: "Zak Krevitt & Sky Goodman",
                description: "The foretold utopia of Web3 reveals itself as a contentious landscape—one where queer expression both flourishes and falls victim to praticable patterns of erasure.",
                thumbnailPath: ["media/home/thumbnails-v2/queering-the-web3/3.webp", "media/home/thumbnails-v2/queering-the-web3/1.webp", "media/home/thumbnails-v2/queering-the-web3/2.webp"],
                thumbnailPathMobile: "media/home/thumbnails-v2-mobile/queering-web3.webp",
                buttonPath: "media/home/buttons/15-button-queering-the-web3.png",
                pagePath: "/queering-the-web3",
                artists: ["Zak Krevitt", "Sky Goodman"],
                artworks: ["Digital Artifacts", "Digital Kinship", "Future Possibilities"],
                quote: "\"The foretold utopia of Web3 reveals itself as a contentious landscape—one where queer expression both flourishes and falls victim to praticable patterns of erasure.\"",
        },
        {
                title: "Chaos Agents",
                subtitle: "Rocco Gallo & Perfect Loop",
                description: "Digital art has long served as a crucible for conceptual experimentation, where computation, probability, and algorithmic logic combine to generate aesthetic forms grounded in chance and indeterminacy.",
                thumbnailPath: ["media/chaos-agents/about-1/about-1.webp", "media/chaos-agents/about-2/about-1.webp", "media/chaos-agents/about-3/about-1.webp"],
                thumbnailPathMobile: "media/chaos-agents/main-cover.webp",
                buttonPath: "media/home/buttons/15-button-chaos-agents.png",
                pagePath: "/chaos-agents",
                artists: ["Rocco Gallo", "Perfect Loop"],
                artworks: ["Nano", "Floppy Drive", "Mushroom nightmare"],
                quote: "Generative art offers a quiet form of resistance. It disrupts visual predictability by reintroducing randomness—not as chaotic noise, but as a creative force.",
        },
        {
                title: "Virality Overnight",
                subtitle: "Riniifish & Woc",
                description: "In the web3 ecosystem, digital artists navigate a fundamental paradox between permanence and vitality. With one hand, they engage a blockchain that derives its authority from immutable, decentralized records; with the other, they respond to an attention economy driven by novelty and hype.",
                thumbnailPath: ["media/virality-overnight/about-3/about-1.webp", "media/virality-overnight/about-1/about-1.webp", "media/virality-overnight/about-2/about-1.webp"],
                thumbnailPathMobile: "media/home/thumbnails-v2-mobile/virality-overnight.webp",
                buttonPath: "media/home/buttons/16-button-virality-overnight.png",
                pagePath: "/virality-overnight",
                artists: ["Riniifish", "Woc"],
                artworks: [],
                quote: "Is virality constructing a new system of artistic validation, or does it merely offer a mirage of recognition?",
        },
        {
                title: "Every Creation is Loss",
                subtitle: "Chepertom & Asdrúbal Gomez",
                description: "Cloud storage, blockchain immutability, and promises of data immortality all reflect digital culture's obsession with permanence. This mindset faces a direct challenge from artists who deliberately embrace entropy and digital erosion.",
                thumbnailPath: [
                        "media/every-creation-is-loss/artwork-grid-1/artwork-grid-1.webp",
                        "media/every-creation-is-loss/artwork-grid-1/artwork-grid-2.webp",
                        "media/every-creation-is-loss/artwork-grid-1/artwork-grid-3.webp"
                ],
                thumbnailPathMobile: "media/home/thumbnails-v2-mobile/every-creation-is-loss.webp",
                buttonPath: "media/home/buttons/17-button-every-creation-is-loss.png",
                pagePath: "/every-creation-is-loss",
                artists: ["Chepertom", "Asdrúbal Gomez"],
                artworks: ["Artwork 1", "Artwork 2", "Artwork 3"],
                quote: "\"Digital erosion is not merely an aesthetic choice, but a calculated resistance to imposed permanence\"",
        }
];